### ISSUE TITLE
Random number is negative

### ISSUE THREAD

**Issue by topahl** [topahl/customSWING#1]
Seed: 8310
testSetIcon 4957 (swing.TestTLabel)

> **java.lang.IllegalArgumentException: Width (-1) and height (9974) cannot be <= 0**
>   at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
>   at java.awt.image.BufferedImage.<init>(BufferedImage.java:340)
>   at swing.TestTLabel.testSetIcon(TestTLabel.java:101)

**Comment by topahl** [comment]
SEED: 5784
testSetIcon 1022 (swing.TestTLabel)

> **java.lang.IllegalArgumentException: Width (0) and height (5883) cannot be <= 0**
>     at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
>     at java.awt.image.BufferedImage.<init>(BufferedImage.java:340)
>     at com.topahl.cutomSWING.swing.TLabel.setIcon(TLabel.java:89)
